flowchart TD
  AppModule-->MUserModule
  MUserModule-->UsersModule
  UsersModule-->ConfigHostModule
  MUserModule-->AccountsModule
  AccountsModule-->ConfigHostModule
  MUserModule-->UserPreferencesModule
  UserPreferencesModule-->ConfigHostModule
  MUserModule-->ConfigHostModule
  AppModule-->MApplicationModule
  MApplicationModule-->ApplicationsModule
  ApplicationsModule-->ConfigHostModule
  MApplicationModule-->NotificationCategoriesModule
  NotificationCategoriesModule-->ConfigHostModule
  MApplicationModule-->ConfigHostModule
  AppModule-->MNotificationModule
  MNotificationModule-->NotificationsModule
  NotificationsModule-->ClientsModule
  ClientsModule-->ConfigModule
  ConfigModule-->ConfigHostModule
  ClientsModule-->ConfigHostModule
  NotificationsModule-->ConfigHostModule
  MNotificationModule-->TemplatesModule
  TemplatesModule-->ConfigHostModule
  MNotificationModule-->ConfigHostModule
  AppModule-->ConfigHostModule