flowchart TD
  AppModule-->NotificationsModule
  NotificationsModule-->NotificationFactoryModule
  NotificationFactoryModule-->TemplateModule
  NotificationFactoryModule-->UserPreferenceModule
  AppModule-->ApplicationsModule