flowchart TD
  AuthModule-->JwtModule
  JwtModule-->AuthModule
  JwtModule-->ConfigHostModule
  ConfigHostModule-->AuthModule
  ConfigHostModule-->JwtModule
  AuthModule-->ConfigHostModule
  AppModule-->AuthModule
  AppModule-->MUserModule
  MUserModule-->UsersModule
  UsersModule-->AuthModule
  UsersModule-->JwtModule
  UsersModule-->ConfigHostModule
  MUserModule-->AccountsModule
  AccountsModule-->NotificationsModule
  NotificationsModule-->TemplatesModule
  TemplatesModule-->AuthModule
  TemplatesModule-->JwtModule
  TemplatesModule-->ConfigHostModule
  NotificationsModule-->ClientsModule
  ClientsModule-->ConfigModule
  ConfigModule-->ConfigHostModule
  ConfigModule-->AuthModule
  ConfigModule-->JwtModule
  ClientsModule-->AuthModule
  ClientsModule-->JwtModule
  ClientsModule-->ConfigHostModule
  NotificationsModule-->AuthModule
  NotificationsModule-->JwtModule
  NotificationsModule-->ConfigHostModule
  AccountsModule-->UserPreferencesModule
  UserPreferencesModule-->AuthModule
  UserPreferencesModule-->JwtModule
  UserPreferencesModule-->ConfigHostModule
  AccountsModule-->AuthModule
  AccountsModule-->JwtModule
  AccountsModule-->ConfigHostModule
  MUserModule-->UserPreferencesModule
  MUserModule-->AuthModule
  MUserModule-->JwtModule
  MUserModule-->ConfigHostModule
  AppModule-->MApplicationModule
  MApplicationModule-->ApplicationsModule
  ApplicationsModule-->AuthModule
  ApplicationsModule-->JwtModule
  ApplicationsModule-->ConfigHostModule
  MApplicationModule-->NotificationCategoriesModule
  NotificationCategoriesModule-->AuthModule
  NotificationCategoriesModule-->JwtModule
  NotificationCategoriesModule-->ConfigHostModule
  MApplicationModule-->AuthModule
  MApplicationModule-->JwtModule
  MApplicationModule-->ConfigHostModule
  AppModule-->MNotificationModule
  MNotificationModule-->NotificationsModule
  MNotificationModule-->TemplatesModule
  MNotificationModule-->AuthModule
  MNotificationModule-->JwtModule
  MNotificationModule-->ConfigHostModule
  AppModule-->TemplatesModule
  AppModule-->JwtModule
  AppModule-->ConfigHostModule