flowchart TD
  AppModule-->MNotificationSendersModule
  MNotificationSendersModule-->ClientsModule
  ClientsModule-->ConfigModule
  ConfigModule-->ConfigHostModule
  ClientsModule-->ConfigHostModule
  MNotificationSendersModule-->ConfigHostModule
  AppModule-->ConfigHostModule