version: "3.8"

services:
  mailpit:
    image: axllent/mailpit:latest
    container_name: mailpit
    restart: unless-stopped
    volumes:
      - ./data:/data # Persistent storage for MailPit data
    ports:
      - 8025:8025 # Web UI accessible at http://localhost:8025
      - 1025:1025 # SMTP server accessible at localhost:1025
    environment:
      MP_MAX_MESSAGES: 5000 # Maximum number of stored messages
      MP_SMTP_AUTH_ACCEPT_ANY: 1 # Accept any SMTP authentication
      MP_SMTP_AUTH_ALLOW_INSECURE: 1 # Allow insecure connections for SMTP
    entrypoint: >
      sh -c "
      echo '------- MailPit is running --------';
      echo '|                                 |';
      echo '|  Web UI: http://localhost:8025  |';
      echo '|  SMTP  : localhost:1025         |';
      echo '|                                 |';
      echo '-----------------------------------';
      /mailpit"
