import Head from "next/head";

import { useClient } from "@/modules/common/hooks/useClient";
import RichTextEditor from "@/modules/template-engine/rich-text-editor/RichTextEditor";
import useEditor from "@/modules/template-engine/rich-text-editor/useEditor";
import { Button } from "@mui/material";
import { signIn, signOut, useSession } from "next-auth/react";
import styles from "./index.module.css";

export default function Home() {
  const { data: session, status } = useSession();
  const { isClientLoaded } = useClient();
  const editor = useEditor();

  if (!isClientLoaded || status === "loading") return null;
  if (status === "unauthenticated") {
    void signIn("logto");
    return null;
  }
  if (!editor) return null;
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <p>{JSON.stringify(session)}</p>
        <RichTextEditor editor={editor} />
        <Button
          variant="contained"
          color="primary"
          onClick={async () => {
            console.log(editor.getJSON());
            await navigator.clipboard.writeText(
              JSON.stringify(editor.getJSON())
            );
          }}
        >
          getJson
        </Button>
        <Button
          variant="contained"
          color="primary"
          onClick={async () => {
            console.log(
              editor.getText({
                blockSeparator: "\n",
              })
            );
            await navigator.clipboard.writeText(
              editor.getText({
                blockSeparator: "\n",
              })
            );
          }}
        >
          get text
        </Button>
        <Button
          variant="contained"
          color="primary"
          onClick={() => {
            void signOut();
          }}
        >
          sign out
        </Button>
      </main>
    </>
  );
}
