version: "3.8"
services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672" # Default RabbitMQ AMQP port
      - "15672:15672" # Management UI port
    environment:
      RABBITMQ_DEFAULT_USER: admin # Default username
      RABBITMQ_DEFAULT_PASS: admin # Default password
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - rabbitmq_logs:/var/log/rabbitmq
    entrypoint: >
      sh -c "
      echo '----------------------------------------------';
      echo '|                                            |';
      echo '|         Local RabbitMQ is running          |';
      echo '|                                            |';
      echo '|  Management UI: http://localhost:15672     |';
      echo '|  AMQP Port     : localhost:5672            |';
      echo '|  Username      : admin                     |';
      echo '|  Password      : admin                     |';
      echo '|                                            |';
      echo '----------------------------------------------';
      rabbitmq-server"
volumes:
  rabbitmq_data:
  rabbitmq_logs:
